name: Trigger Deploy
on:
  issue_comment:
    types: [created, edited, deleted]
  issues:
    types:
      [opened, deleted, edited, labeled, unlabeled, milestoned, demilestoned]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/phshy0607/blog/actions/workflows/gh_pages.yml/dispatches \
          -d '{"ref": "master"}'
